export enum AuditEntity {
  PROPERTY = 'PROPERTY',
  LANDLORD = 'LANDLORD',
  USER = 'USER',
  IMAGE = 'IMAGE',
  AUTH = 'AUTH',
  HOSTEL_ROOM = 'HOSTEL_ROOM',
  BOOKING = 'BOOKING',
  DISTRICT = 'DISTRICT',
}